name = "Simple Resume"
license = "MIT"
licenselink = "https://github.com/tylerjlawson/simple-resume/blob/master/LICENSE"
description = ""
homepage = "https://github.com/tylerjlawson/simple-resume/"
tags = ["cv", "resume", "minimalist"]
min_version = "0.41.0"

[author]
  name = "Tyler Lawson"
  homepage = "https://tyler-lawson.com"
